const john = {
  ERROR: "",
  GROUP: {
    DRAG_SORT: "0",
    source_required: "0",
    DISPLAY_NAME_INSTRUCTION: "the title of the sarticel",
    SHORT_DESC_REQUIRED: "0",
    site_id: "441",
    ASSOCIATION_INSTRUCTION: "",
    extra3_name: "Format",
    long_desc_instruction: "Text for body of article(if needed)",
    GT_FLEX2_NAME: "",
    GROUPS: "0",
    EXTRA2_EDIT_DD: "1",
    type_name: "User Type",
    EXTRA2_REQUIRED: "1",
    drag_sort: "0",
    name: "Resource Center",
    base_location: "resources",
    source_instruction: "",
    PRIV_ID: null,
    STATUS_ID: 1,
    groups_instruction: "",
    priv_required: "0",
    short_desc_required: "0",
    ASSOCIATION_REQUIRED: "0",
    display_name_instruction: "the title of the sarticel",
    extra3_edit_dd: "1",
    file2_required: "0",
    PAGE_URL: null,
    AUTHOR_NAME: "Author",
    MAPPING_INSTRUCTION: "The topics to tag the article with",
    SOURCE_REQUIRED: "0",
    mapping_edit: "1",
    extra3_required: "1",
    POST_DATE_REQUIRED: "1",
    FILE2_REQUIRED: "0",
    USER_ID: "14",
    short_desc_name: "Summary",
    association: "0",
    PARSER_ID: null,
    file2_instruction: "",
    EXTRA2_NAME: "Audience",
    TYPE_ID: "1",
    gt_flex5_name: "",
    status_id: 1,
    long_desc_required: "0",
    EMAIL_SUBJECT: "New Document",
    POST_DATE_INSTRUCTION: "The date of the article",
    extra1_required: "1",
    TYPES_INSTRUCTION: "",
    save_file_without_id: "0",
    types_instruction: "",
    GT_FLEX4_NAME: "",
    EXTRA1_NAME: "Industry",
    EXTRA2_INSTRUCTION: "The audience the article is tagged with",
    author_required: "0",
    mapping_required: "1",
    SHORT_DESC_INSTRUCTION: "Summary of article",
    URL: "",
    AUTHOR_REQUIRED: "0",
    EXTRA2: ["Partners", "Clients"],
    SHORT_DESC_NAME: "Summary",
    TYPE_NAME: "User Type",
    DESCRIPTION: "Document manager for the resource Center",
    use_crypt: "1",
    CSS_CLASS_NAME: null,
    EXTRA3_INSTRUCTION: "the format of the article",
    DISPLAY_NAME_REQUIRED: "1",
    MAPPINGS: [
      { KEY: "Covi-19", ID: "242", PARENT_ID: null, EXTRA_VALUE: null },
      { KEY: "Financial", ID: "243", PARENT_ID: null, EXTRA_VALUE: null },
      { KEY: "Stocks", ID: "244", PARENT_ID: null, EXTRA_VALUE: null },
      { KEY: "markets", ID: "245", PARENT_ID: null, EXTRA_VALUE: null },
      { KEY: "pharma", ID: "246", PARENT_ID: null, EXTRA_VALUE: null },
      { KEY: "education", ID: "247", PARENT_ID: null, EXTRA_VALUE: null },
      {
        KEY: "green initiatives",
        ID: "248",
        PARENT_ID: null,
        EXTRA_VALUE: null,
      },
      { KEY: "politics", ID: "249", PARENT_ID: null, EXTRA_VALUE: null },
      { KEY: "Trending", ID: "250", PARENT_ID: null, EXTRA_VALUE: null },
    ],
    priv_name: "",
    css_class_name: null,
    GROUP_ID: "4050",
    ASSOCIATION: "0",
    FILE2_NAME: "",
    GROUP_NAME: "User Group",
    post_date_name: "Post Date",
    MAPPING_NAME: "Topics",
    gt_flex1_name: "",
    LONG_DESC_REQUIRED: "0",
    MAPPING_REQUIRED: "1",
    priv_instruction: "",
    use_nl: "0",
    GROUPS_INSTRUCTION: "",
    created: "2020-04-06 14:34:52",
    GT_FLEX1_NAME: "",
    extra2_instruction: "The audience the article is tagged with",
    display_name_required: "1",
    EXTRA3_EDIT_DD: "1",
    DISPLAY_TYPE_ID: "10",
    long_desc_name: "Body Text",
    FILE2_INSTRUCTION: "",
    gt_flex3_name: "",
    post_date_required: "1",
    CREATED: "2020-04-06 14:34:52",
    gt_flex2_name: "",
    SOURCE_INSTRUCTION: "",
    type_id: "1",
    url: "",
    EXTRA1: ["Health", "Finance", "Food"],
    SAVE_FILE_WITHOUT_ID: "0",
    mapping_instruction: "The topics to tag the article with",
    mapping_extra_status: "0",
    USE_CRYPT: "1",
    AUTHOR_INSTRUCTION: "The author of the article",
    site_directory_base: "sanctuary",
    description: "Document manager for the resource Center",
    EXTRA1_INSTRUCTION: "The industry this article is tagged with",
    email_body: "A new document has been posted",
    BASE_LOCATION: "resources",
    mapping_name: "Topics",
    EXTRA1_REQUIRED: "1",
    AUTO_EMAIL: "0",
    user_id: "14",
    SOURCE_NAME: "",
    auto_email: "0",
    author_name: "Author",
    DISPLAY_NAME_NAME: "Title",
    extra1_instruction: "The industry this article is tagged with",
    EXTRA3_NAME: "Format",
    default_display_name: "Resource Center",
    status_name: "Private",
    MAPPING_DIRECTORY: "",
    extra2_required: "1",
    GROUPS_REQUIRED: "0",
    groups_required: "0",
    NAME: "Resource Center",
    association_required: "0",
    extra3_instruction: "the format of the article",
    EXTRA1_EDIT_DD: "1",
    use_time_frame: "1",
    DEFAULT_DISPLAY_NAME: "Resource Center",
    email_subject: "New Document",
    group_id: "4050",
    EMAIL_BODY: "A new document has been posted",
    post_date_instruction: "The date of the article",
    POST_DATE_NAME: "Post Date",
    extra2_edit_dd: "1",
    display_type_id: "10",
    GT_FLEX3_NAME: "",
    SITE_DIRECTORY_BASE: "sanctuary",
    groups: "0",
    LONG_DESC_INSTRUCTION: "Text for body of article(if needed)",
    author_instruction: "The author of the article",
    display_name_name: "Title",
    extra1_edit_dd: "1",
    extra1_name: "Industry",
    parser_id: null,
    TYPES_REQUIRED: "0",
    USE_TIME_FRAME: "1",
    USE_NL: "0",
    GT_FLEX5_NAME: "",
    EXTRA3: ["Webinars", "Industry Update", "Insights"],
    PRIV_REQUIRED: "0",
    PRIV_NAME: "",
    PRIV_INSTRUCTION: "",
    association_instruction: "",
    EXTRA3_REQUIRED: "1",
    types: "0",
    priv_id: null,
    LONG_DESC_NAME: "Body Text",
    MAPPING_EXTRA_STATUS: "0",
    types_required: "0",
    STATUS_NAME: "Private",
    mapping_directory: "",
    extra2_name: "Audience",
    MAPPING_EDIT: "1",
    page_url: null,
    group_name: "User Group",
    gt_flex4_name: "",
    file2_name: "",
    source_name: "",
    short_desc_instruction: "Summary of article",
    TYPES: "0",
    SITE_ID: "441",
  },
  SQL:
    "\n\tselect\n\t*, date_format(post_date, ?) post_date_format, date_format(entrydate, ?) entrydate_format, year(post_date) year\n\tfrom file_enity\n\twhere group_id = ?\n\t and STATUS = ?  and ARCHIVE_STATUS = ? \n\t\tand (tf_start is null or tf_start = '0000-00-00 00:00:00' or tf_start < now())\n        \tand (tf_end is null or tf_end = '0000-00-00 00:00:00' or tf_end > now())\n\t\t\n\t\n\torder by entrydate desc\n\t",
  DATA: [
    {
      extra1: "Health",
      STATUS: "1",
      ENITY_ID: "602906",
      HREF: "https://www.youtube.com/results?search_query=cnbc",
      post_date_format: "08/05/2019",
      terms_id: null,
      TF_END: null,
      ENTRYDATE: "2020-04-07 10:40:10",
      archive_status: "0",
      EXTRA1: "Health",
      mail_processed: "0",
      sort_order: "0",
      MAIL_PROCESSED: "0",
      TERMS_ID: null,
      long_desc: "",
      PRIV_ID: null,
      POST_DATE: "2019-08-05 00:00:00",
      extra3: "Webinars",
      post_date: "2019-08-05 00:00:00",
      user_id: "14",
      SOURCE: null,
      source: null,
      PAGE_URL: null,
      author: "",
      USER_ID: "14",
      ARCHIVE_STATUS: "0",
      STAMP_ID: null,
      map_user_id: null,
      SHORT_DESC: "",
      group_id: "4050",
      FILE_HREF:
        "/data/documents/FG/sanctuary/resources/602906_photo-1586264470882-e23232308cbb.webp",
      year: "2019",
      SORT_ORDER: "0",
      ENTRYDATE_FORMAT: "04/07/2020",
      LONG_DESC: "",
      FILE2_HREF: "",
      file_name: "602906_photo-1586264470882-e23232308cbb.webp",
      short_desc: "",
      entrydate_format: "04/07/2020",
      file_name2: null,
      EXTRA2: "Partners",
      AUTHOR: "",
      LINK: "https://www.youtube.com/results?search_query=cnbc",
      EXTRA3: "Webinars",
      DISPLAY_NAME:
        "Parturient montes nascetur ridiculus mus mauris vitae ultricies.",
      FILE_NAME: "602906_photo-1586264470882-e23232308cbb.webp",
      priv_id: null,
      YEAR: "2019",
      status: "1",
      GROUP_ID: "4050",
      tf_start: null,
      tf_end: null,
      entrydate: "2020-04-07 10:40:10",
      stamp_id: null,
      FILE_EXTENSHION_ID: "1",
      MAPPING_IDS: [
        { ID: "247", NAME: "education" },
        { ID: "250", NAME: "Trending" },
      ],
      TF_START: null,
      page_url: null,
      link: "https://www.youtube.com/results?search_query=cnbc",
      extra2: "Partners",
      file_extenshion_id: "1",
      enity_id: "602906",
      display_name:
        "Parturient montes nascetur ridiculus mus mauris vitae ultricies.",
      FILE_NAME2: null,
      MAP_USER_ID: null,
      POST_DATE_FORMAT: "08/05/2019",
    },
    {
      extra1: "Finance",
      STATUS: "1",
      ENITY_ID: "602905",
      HREF: "https://www.youtube.com/results?search_query=cnbc",
      post_date_format: "08/05/2019",
      terms_id: null,
      TF_END: null,
      ENTRYDATE: "2020-04-07 10:39:40",
      archive_status: "0",
      EXTRA1: "Finance",
      mail_processed: "0",
      sort_order: "0",
      MAIL_PROCESSED: "0",
      TERMS_ID: null,
      long_desc: "",
      PRIV_ID: null,
      POST_DATE: "2019-08-05 00:00:00",
      extra3: "Webinars",
      post_date: "2019-08-05 00:00:00",
      user_id: "14",
      SOURCE: null,
      source: null,
      PAGE_URL: null,
      author: "",
      USER_ID: "14",
      ARCHIVE_STATUS: "0",
      STAMP_ID: null,
      map_user_id: null,
      SHORT_DESC: "",
      group_id: "4050",
      FILE_HREF: "",
      year: "2019",
      SORT_ORDER: "0",
      ENTRYDATE_FORMAT: "04/07/2020",
      LONG_DESC: "",
      FILE2_HREF: "",
      file_name: null,
      short_desc: "",
      entrydate_format: "04/07/2020",
      file_name2: null,
      EXTRA2: "Partners",
      AUTHOR: "",
      LINK: "https://www.youtube.com/results?search_query=cnbc",
      EXTRA3: "Webinars",
      DISPLAY_NAME: "Lorem ipsum dolor sit amet",
      FILE_NAME: null,
      priv_id: null,
      YEAR: "2019",
      status: "1",
      GROUP_ID: "4050",
      tf_start: null,
      tf_end: null,
      entrydate: "2020-04-07 10:39:40",
      stamp_id: null,
      FILE_EXTENSHION_ID: "1",
      MAPPING_IDS: [
        { ID: "246", NAME: "pharma" },
        { ID: "249", NAME: "politics" },
        { ID: "250", NAME: "Trending" },
      ],
      TF_START: null,
      page_url: null,
      link: "https://www.youtube.com/results?search_query=cnbc",
      extra2: "Partners",
      file_extenshion_id: "1",
      enity_id: "602905",
      display_name: "Lorem ipsum dolor sit amet",
      FILE_NAME2: null,
      MAP_USER_ID: null,
      POST_DATE_FORMAT: "08/05/2019",
    },
    {
      extra1: "Food",
      STATUS: "1",
      ENITY_ID: "602904",
      HREF: "/cgi-bin/r/util/fg_pickup.pl?ENITY_ID=602904",
      post_date_format: "05/23/2019",
      terms_id: null,
      TF_END: null,
      ENTRYDATE: "2020-04-07 10:34:57",
      archive_status: "0",
      EXTRA1: "Food",
      mail_processed: "0",
      sort_order: "0",
      MAIL_PROCESSED: "0",
      TERMS_ID: null,
      long_desc:
        "Lorem ipsum dolor sit amet, consectetur adipiscing elit, sed do eiusmod tempor incididunt ut labore et dolore magna aliqua. A erat nam at lectus urna duis convallis convallis. Laoreet suspendisse interdum consectetur libero id faucibus nisl tincidunt. Ipsum suspendisse ultrices gravida dictum fusce. Id leo in vitae turpis massa sed elementum tempus. Nec sagittis aliquam malesuada bibendum arcu vitae elementum curabitur. Amet risus nullam eget felis eget nunc lobortis mattis. Leo vel orci porta non pulvinar neque laoreet. Enim blandit volutpat maecenas volutpat. Gravida arcu ac tortor dignissim convallis aenean et tortor at. Enim lobortis scelerisque fermentum dui faucibus in ornare.<br /><br />Parturient montes nascetur ridiculus mus mauris vitae ultricies. Viverra mauris in aliquam sem fringilla. Proin sagittis nisl rhoncus mattis rhoncus urna neque. Parturient montes nascetur ridiculus mus mauris vitae. Dui accumsan sit amet nulla facilisi morbi tempus. Leo integer malesuada nunc vel risus commodo viverra. Leo urna molestie at elementum eu facilisis. Vivamus at augue eget arcu dictum varius. Curabitur gravida arcu ac tortor dignissim convallis aenean et tortor. Lobortis feugiat vivamus at augue eget arcu. Maecenas sed enim ut sem.<br /><br />Faucibus interdum posuere lorem ipsum dolor sit amet consectetur adipiscing. Elementum curabitur vitae nunc sed velit. Purus in mollis nunc sed id semper risus in hendrerit. Posuere urna nec tincidunt praesent. Semper auctor neque vitae tempus quam pellentesque nec nam aliquam. Quam elementum pulvinar etiam non quam lacus. Sit amet consectetur adipiscing elit pellentesque habitant morbi. Lorem sed risus ultricies tristique. Tortor aliquam nulla facilisi cras fermentum odio eu feugiat pretium. Duis convallis convallis tellus id. Fermentum leo vel orci porta non pulvinar neque laoreet suspendisse. Adipiscing bibendum est ultricies integer quis auctor elit sed vulputate. Augue neque gravida in fermentum et. Tellus in metus vulputate eu scelerisque. Iaculis at erat pellentesque adipiscing commodo elit at. Rutrum tellus pellentesque eu tincidunt tortor aliquam nulla. Elementum eu facilisis sed odio. Lacus sed turpis tincidunt id aliquet risus feugiat in.<br /><br />Et tortor consequat id porta nibh venenatis cras sed felis. Viverra orci sagittis eu volutpat odio facilisis mauris. Orci phasellus egestas tellus rutrum tellus pellentesque. Sit amet risus nullam eget felis eget nunc lobortis. Proin sagittis nisl rhoncus mattis rhoncus urna neque. Lacus luctus accumsan tortor posuere ac ut consequat. Lectus proin nibh nisl condimentum id venenatis a condimentum. Eros donec ac odio tempor orci dapibus ultrices in. Blandit libero volutpat sed cras. Augue neque gravida in fermentum et sollicitudin ac. Sed risus pretium quam vulputate dignissim suspendisse in. Urna nunc id cursus metus aliquam eleifend. Convallis a cras semper auctor neque vitae tempus quam pellentesque. Purus in mollis nunc sed. Vulputate enim nulla aliquet porttitor lacus luctus accumsan. Dapibus ultrices in iaculis nunc sed. Volutpat blandit aliquam etiam erat. Adipiscing diam donec adipiscing tristique risus nec. Lacus viverra vitae congue eu consequat ac felis donec.<br /><br />Consectetur a erat nam at lectus. Quam id leo in vitae turpis massa sed elementum. Maecenas accumsan lacus vel facilisis volutpat est velit egestas dui. Eget aliquet nibh praesent tristique magna sit amet purus gravida. Hendrerit gravida rutrum quisque non tellus orci ac. Vitae justo eget magna fermentum iaculis. Magna ac placerat vestibulum lectus mauris. Bibendum est ultricies integer quis auctor elit sed. Eget aliquet nibh praesent tristique magna sit amet purus gravida. Iaculis nunc sed augue lacus viverra vitae. Egestas diam in arcu cursus euismod quis viverra nibh cras. Convallis posuere morbi leo urna molestie at. Odio ut sem nulla pharetra diam sit amet nisl suscipit. Purus sit amet volutpat consequat.<br /><br />Ornare suspendisse sed nisi lacus. Faucibus in ornare quam viverra orci sagittis eu. Facilisi cras fermentum odio eu feugiat pretium nibh ipsum. In mollis nunc sed id semper risus. Suscipit tellus mauris a diam maecenas sed enim ut sem. Vel risus commodo viverra maecenas accumsan lacus vel facilisis. Dictum fusce ut placerat orci nulla pellentesque dignissim enim sit. Vitae ultricies leo integer malesuada nunc. Ac tincidunt vitae semper quis lectus nulla at volutpat diam. Vitae tempus quam pellentesque nec nam. Nulla facilisi etiam dignissim diam quis enim lobortis. Euismod lacinia at quis risus. Fringilla urna porttitor rhoncus dolor purus non.<br /><br />Dui id ornare arcu odio ut sem nulla pharetra. Lorem sed risus ultricies tristique nulla aliquet. Tellus molestie nunc non blandit massa enim. Accumsan in nisl nisi scelerisque eu. Congue nisi vitae suscipit tellus mauris a diam maecenas sed. Diam volutpat commodo sed egestas egestas fringilla phasellus faucibus scelerisque. Aliquet nec ullamcorper sit amet. Morbi quis commodo odio aenean sed adipiscing diam donec. Dictum non consectetur a erat nam. Sed viverra ipsum nunc aliquet bibendum enim facilisis gravida.",
      PRIV_ID: null,
      POST_DATE: "2019-05-23 00:00:00",
      extra3: "Insights",
      post_date: "2019-05-23 00:00:00",
      user_id: "14",
      SOURCE: null,
      source: null,
      PAGE_URL: null,
      author: "John Doe",
      USER_ID: "14",
      ARCHIVE_STATUS: "0",
      STAMP_ID: null,
      map_user_id: null,
      SHORT_DESC:
        "Id leo in vitae turpis massa. Condimentum lacinia quis vel eros donec.",
      group_id: "4050",
      FILE_HREF:
        "/data/documents/FG/sanctuary/resources/602904_photo-1586199048510-60f2d45dfebe.webp",
      year: "2019",
      SORT_ORDER: "0",
      ENTRYDATE_FORMAT: "04/07/2020",
      LONG_DESC:
        "Lorem ipsum dolor sit amet, consectetur adipiscing elit, sed do eiusmod tempor incididunt ut labore et dolore magna aliqua. A erat nam at lectus urna duis convallis convallis. Laoreet suspendisse interdum consectetur libero id faucibus nisl tincidunt. Ipsum suspendisse ultrices gravida dictum fusce. Id leo in vitae turpis massa sed elementum tempus. Nec sagittis aliquam malesuada bibendum arcu vitae elementum curabitur. Amet risus nullam eget felis eget nunc lobortis mattis. Leo vel orci porta non pulvinar neque laoreet. Enim blandit volutpat maecenas volutpat. Gravida arcu ac tortor dignissim convallis aenean et tortor at. Enim lobortis scelerisque fermentum dui faucibus in ornare.<br /><br />Parturient montes nascetur ridiculus mus mauris vitae ultricies. Viverra mauris in aliquam sem fringilla. Proin sagittis nisl rhoncus mattis rhoncus urna neque. Parturient montes nascetur ridiculus mus mauris vitae. Dui accumsan sit amet nulla facilisi morbi tempus. Leo integer malesuada nunc vel risus commodo viverra. Leo urna molestie at elementum eu facilisis. Vivamus at augue eget arcu dictum varius. Curabitur gravida arcu ac tortor dignissim convallis aenean et tortor. Lobortis feugiat vivamus at augue eget arcu. Maecenas sed enim ut sem.<br /><br />Faucibus interdum posuere lorem ipsum dolor sit amet consectetur adipiscing. Elementum curabitur vitae nunc sed velit. Purus in mollis nunc sed id semper risus in hendrerit. Posuere urna nec tincidunt praesent. Semper auctor neque vitae tempus quam pellentesque nec nam aliquam. Quam elementum pulvinar etiam non quam lacus. Sit amet consectetur adipiscing elit pellentesque habitant morbi. Lorem sed risus ultricies tristique. Tortor aliquam nulla facilisi cras fermentum odio eu feugiat pretium. Duis convallis convallis tellus id. Fermentum leo vel orci porta non pulvinar neque laoreet suspendisse. Adipiscing bibendum est ultricies integer quis auctor elit sed vulputate. Augue neque gravida in fermentum et. Tellus in metus vulputate eu scelerisque. Iaculis at erat pellentesque adipiscing commodo elit at. Rutrum tellus pellentesque eu tincidunt tortor aliquam nulla. Elementum eu facilisis sed odio. Lacus sed turpis tincidunt id aliquet risus feugiat in.<br /><br />Et tortor consequat id porta nibh venenatis cras sed felis. Viverra orci sagittis eu volutpat odio facilisis mauris. Orci phasellus egestas tellus rutrum tellus pellentesque. Sit amet risus nullam eget felis eget nunc lobortis. Proin sagittis nisl rhoncus mattis rhoncus urna neque. Lacus luctus accumsan tortor posuere ac ut consequat. Lectus proin nibh nisl condimentum id venenatis a condimentum. Eros donec ac odio tempor orci dapibus ultrices in. Blandit libero volutpat sed cras. Augue neque gravida in fermentum et sollicitudin ac. Sed risus pretium quam vulputate dignissim suspendisse in. Urna nunc id cursus metus aliquam eleifend. Convallis a cras semper auctor neque vitae tempus quam pellentesque. Purus in mollis nunc sed. Vulputate enim nulla aliquet porttitor lacus luctus accumsan. Dapibus ultrices in iaculis nunc sed. Volutpat blandit aliquam etiam erat. Adipiscing diam donec adipiscing tristique risus nec. Lacus viverra vitae congue eu consequat ac felis donec.<br /><br />Consectetur a erat nam at lectus. Quam id leo in vitae turpis massa sed elementum. Maecenas accumsan lacus vel facilisis volutpat est velit egestas dui. Eget aliquet nibh praesent tristique magna sit amet purus gravida. Hendrerit gravida rutrum quisque non tellus orci ac. Vitae justo eget magna fermentum iaculis. Magna ac placerat vestibulum lectus mauris. Bibendum est ultricies integer quis auctor elit sed. Eget aliquet nibh praesent tristique magna sit amet purus gravida. Iaculis nunc sed augue lacus viverra vitae. Egestas diam in arcu cursus euismod quis viverra nibh cras. Convallis posuere morbi leo urna molestie at. Odio ut sem nulla pharetra diam sit amet nisl suscipit. Purus sit amet volutpat consequat.<br /><br />Ornare suspendisse sed nisi lacus. Faucibus in ornare quam viverra orci sagittis eu. Facilisi cras fermentum odio eu feugiat pretium nibh ipsum. In mollis nunc sed id semper risus. Suscipit tellus mauris a diam maecenas sed enim ut sem. Vel risus commodo viverra maecenas accumsan lacus vel facilisis. Dictum fusce ut placerat orci nulla pellentesque dignissim enim sit. Vitae ultricies leo integer malesuada nunc. Ac tincidunt vitae semper quis lectus nulla at volutpat diam. Vitae tempus quam pellentesque nec nam. Nulla facilisi etiam dignissim diam quis enim lobortis. Euismod lacinia at quis risus. Fringilla urna porttitor rhoncus dolor purus non.<br /><br />Dui id ornare arcu odio ut sem nulla pharetra. Lorem sed risus ultricies tristique nulla aliquet. Tellus molestie nunc non blandit massa enim. Accumsan in nisl nisi scelerisque eu. Congue nisi vitae suscipit tellus mauris a diam maecenas sed. Diam volutpat commodo sed egestas egestas fringilla phasellus faucibus scelerisque. Aliquet nec ullamcorper sit amet. Morbi quis commodo odio aenean sed adipiscing diam donec. Dictum non consectetur a erat nam. Sed viverra ipsum nunc aliquet bibendum enim facilisis gravida.",
      FILE2_HREF: "",
      file_name: "602904_photo-1586199048510-60f2d45dfebe.webp",
      short_desc:
        "Id leo in vitae turpis massa. Condimentum lacinia quis vel eros donec.",
      entrydate_format: "04/07/2020",
      file_name2: null,
      EXTRA2: "Clients",
      AUTHOR: "John Doe",
      LINK: "",
      EXTRA3: "Insights",
      DISPLAY_NAME: "Mi bibendum neque",
      FILE_NAME: "602904_photo-1586199048510-60f2d45dfebe.webp",
      priv_id: null,
      YEAR: "2019",
      status: "1",
      GROUP_ID: "4050",
      tf_start: null,
      tf_end: null,
      entrydate: "2020-04-07 10:34:57",
      stamp_id: null,
      FILE_EXTENSHION_ID: "1",
      MAPPING_IDS: [
        { ID: "248", NAME: "green initiatives" },
        { ID: "245", NAME: "markets" },
        { ID: "250", NAME: "Trending" },
      ],
      TF_START: null,
      page_url: null,
      link: "",
      extra2: "Clients",
      file_extenshion_id: "1",
      enity_id: "602904",
      display_name: "Mi bibendum neque",
      FILE_NAME2: null,
      MAP_USER_ID: null,
      POST_DATE_FORMAT: "05/23/2019",
    },
    {
      extra1: "Finance",
      STATUS: "1",
      ENITY_ID: "602902",
      HREF: "/cgi-bin/r/util/fg_pickup.pl?ENITY_ID=602902",
      post_date_format: "07/01/2019",
      terms_id: null,
      TF_END: null,
      ENTRYDATE: "2020-04-07 10:32:08",
      archive_status: "0",
      EXTRA1: "Finance",
      mail_processed: "0",
      sort_order: "0",
      MAIL_PROCESSED: "0",
      TERMS_ID: null,
      long_desc:
        "Lorem ipsum dolor sit amet, consectetur adipiscing elit, sed do eiusmod tempor incididunt ut labore et dolore magna aliqua. Tortor vitae purus faucibus ornare suspendisse sed nisi lacus sed. Sed vulputate odio ut enim blandit volutpat maecenas. Lacus vel facilisis volutpat est velit. Facilisis magna etiam tempor orci eu lobortis elementum nibh tellus. Sit amet purus gravida quis blandit turpis. Quam viverra orci sagittis eu volutpat odio facilisis. Quis viverra nibh cras pulvinar mattis. Nibh tellus molestie nunc non blandit massa. Duis ut diam quam nulla. Ligula ullamcorper malesuada proin libero nunc. Viverra nam libero justo laoreet sit amet cursus sit amet. Maecenas sed enim ut sem. Mauris ultrices eros in cursus turpis. Condimentum lacinia quis vel eros donec ac odio tempor. Mattis vulputate enim nulla aliquet porttitor lacus luctus. Dictum sit amet justo donec enim diam vulputate ut. Facilisis magna etiam tempor orci eu lobortis elementum. Pulvinar pellentesque habitant morbi tristique senectus et netus et.<br /><br />Ultricies leo integer malesuada nunc vel risus commodo viverra maecenas. Amet consectetur adipiscing elit ut aliquam purus sit amet. In fermentum et sollicitudin ac orci phasellus egestas tellus rutrum. Non curabitur gravida arcu ac tortor dignissim convallis aenean et. Bibendum ut tristique et egestas. Phasellus vestibulum lorem sed risus ultricies. Facilisi morbi tempus iaculis urna id volutpat. Amet luctus venenatis lectus magna fringilla urna porttitor. Volutpat lacus laoreet non curabitur gravida arcu ac tortor. Odio pellentesque diam volutpat commodo sed egestas egestas fringilla. Id diam maecenas ultricies mi eget mauris pharetra et ultrices. Venenatis tellus in metus vulputate eu scelerisque. Nunc sed id semper risus in hendrerit gravida rutrum. Sed lectus vestibulum mattis ullamcorper velit sed ullamcorper morbi tincidunt. Lectus quam id leo in vitae turpis massa.<br /><br />Mi bibendum neque egestas congue. Id leo in vitae turpis massa. Condimentum lacinia quis vel eros donec ac odio tempor orci. Condimentum lacinia quis vel eros donec ac odio tempor. Eu consequat ac felis donec et odio pellentesque diam volutpat. Id consectetur purus ut faucibus pulvinar elementum. Pulvinar mattis nunc sed blandit libero volutpat sed cras ornare. Nisl condimentum id venenatis a condimentum. Congue quisque egestas diam in arcu. Nunc non blandit massa enim nec. Nisl condimentum id venenatis a condimentum vitae sapien pellentesque. In fermentum et sollicitudin ac orci phasellus.<br /><br />Ultrices vitae auctor eu augue. Gravida dictum fusce ut placerat orci nulla pellentesque dignissim. Duis at tellus at urna condimentum mattis. Id donec ultrices tincidunt arcu non. Lectus nulla at volutpat diam ut venenatis tellus in metus. Orci ac auctor augue mauris augue neque gravida in fermentum. Pulvinar pellentesque habitant morbi tristique senectus et netus et malesuada. Augue eget arcu dictum varius duis at consectetur lorem donec. Ut enim blandit volutpat maecenas. Et tortor consequat id porta nibh. Libero justo laoreet sit amet cursus sit amet dictum sit. Ut pharetra sit amet aliquam id diam maecenas. Ultricies tristique nulla aliquet enim tortor at auctor urna. Cras ornare arcu dui vivamus arcu felis bibendum ut tristique. Dictum fusce ut placerat orci nulla pellentesque dignissim. Hendrerit dolor magna eget est lorem ipsum dolor. Quis ipsum suspendisse ultrices gravida dictum.",
      PRIV_ID: null,
      POST_DATE: "2019-07-01 00:00:00",
      extra3: "Insights",
      post_date: "2019-07-01 00:00:00",
      user_id: "14",
      SOURCE: null,
      source: null,
      PAGE_URL: null,
      author: "Jane Doe",
      USER_ID: "14",
      ARCHIVE_STATUS: "0",
      STAMP_ID: null,
      map_user_id: null,
      SHORT_DESC:
        "Lorem ipsum dolor sit amet, consectetur adipiscing elit, sed do eiusmod tempor incididunt ut labore et dolore magna aliqua. Tortor vitae purus faucibus.",
      group_id: "4050",
      FILE_HREF:
        "/data/documents/FG/sanctuary/resources/602902_photo-1586220742613-b731f66f7743.webp",
      year: "2019",
      SORT_ORDER: "0",
      ENTRYDATE_FORMAT: "04/07/2020",
      LONG_DESC:
        "Lorem ipsum dolor sit amet, consectetur adipiscing elit, sed do eiusmod tempor incididunt ut labore et dolore magna aliqua. Tortor vitae purus faucibus ornare suspendisse sed nisi lacus sed. Sed vulputate odio ut enim blandit volutpat maecenas. Lacus vel facilisis volutpat est velit. Facilisis magna etiam tempor orci eu lobortis elementum nibh tellus. Sit amet purus gravida quis blandit turpis. Quam viverra orci sagittis eu volutpat odio facilisis. Quis viverra nibh cras pulvinar mattis. Nibh tellus molestie nunc non blandit massa. Duis ut diam quam nulla. Ligula ullamcorper malesuada proin libero nunc. Viverra nam libero justo laoreet sit amet cursus sit amet. Maecenas sed enim ut sem. Mauris ultrices eros in cursus turpis. Condimentum lacinia quis vel eros donec ac odio tempor. Mattis vulputate enim nulla aliquet porttitor lacus luctus. Dictum sit amet justo donec enim diam vulputate ut. Facilisis magna etiam tempor orci eu lobortis elementum. Pulvinar pellentesque habitant morbi tristique senectus et netus et.<br /><br />Ultricies leo integer malesuada nunc vel risus commodo viverra maecenas. Amet consectetur adipiscing elit ut aliquam purus sit amet. In fermentum et sollicitudin ac orci phasellus egestas tellus rutrum. Non curabitur gravida arcu ac tortor dignissim convallis aenean et. Bibendum ut tristique et egestas. Phasellus vestibulum lorem sed risus ultricies. Facilisi morbi tempus iaculis urna id volutpat. Amet luctus venenatis lectus magna fringilla urna porttitor. Volutpat lacus laoreet non curabitur gravida arcu ac tortor. Odio pellentesque diam volutpat commodo sed egestas egestas fringilla. Id diam maecenas ultricies mi eget mauris pharetra et ultrices. Venenatis tellus in metus vulputate eu scelerisque. Nunc sed id semper risus in hendrerit gravida rutrum. Sed lectus vestibulum mattis ullamcorper velit sed ullamcorper morbi tincidunt. Lectus quam id leo in vitae turpis massa.<br /><br />Mi bibendum neque egestas congue. Id leo in vitae turpis massa. Condimentum lacinia quis vel eros donec ac odio tempor orci. Condimentum lacinia quis vel eros donec ac odio tempor. Eu consequat ac felis donec et odio pellentesque diam volutpat. Id consectetur purus ut faucibus pulvinar elementum. Pulvinar mattis nunc sed blandit libero volutpat sed cras ornare. Nisl condimentum id venenatis a condimentum. Congue quisque egestas diam in arcu. Nunc non blandit massa enim nec. Nisl condimentum id venenatis a condimentum vitae sapien pellentesque. In fermentum et sollicitudin ac orci phasellus.<br /><br />Ultrices vitae auctor eu augue. Gravida dictum fusce ut placerat orci nulla pellentesque dignissim. Duis at tellus at urna condimentum mattis. Id donec ultrices tincidunt arcu non. Lectus nulla at volutpat diam ut venenatis tellus in metus. Orci ac auctor augue mauris augue neque gravida in fermentum. Pulvinar pellentesque habitant morbi tristique senectus et netus et malesuada. Augue eget arcu dictum varius duis at consectetur lorem donec. Ut enim blandit volutpat maecenas. Et tortor consequat id porta nibh. Libero justo laoreet sit amet cursus sit amet dictum sit. Ut pharetra sit amet aliquam id diam maecenas. Ultricies tristique nulla aliquet enim tortor at auctor urna. Cras ornare arcu dui vivamus arcu felis bibendum ut tristique. Dictum fusce ut placerat orci nulla pellentesque dignissim. Hendrerit dolor magna eget est lorem ipsum dolor. Quis ipsum suspendisse ultrices gravida dictum.",
      FILE2_HREF: "",
      file_name: "602902_photo-1586220742613-b731f66f7743.webp",
      short_desc:
        "Lorem ipsum dolor sit amet, consectetur adipiscing elit, sed do eiusmod tempor incididunt ut labore et dolore magna aliqua. Tortor vitae purus faucibus.",
      entrydate_format: "04/07/2020",
      file_name2: null,
      EXTRA2: "Partners",
      AUTHOR: "Jane Doe",
      LINK: "",
      EXTRA3: "Insights",
      DISPLAY_NAME: "Ultricies leo integer malesuada",
      FILE_NAME: "602902_photo-1586220742613-b731f66f7743.webp",
      priv_id: null,
      YEAR: "2019",
      status: "1",
      GROUP_ID: "4050",
      tf_start: null,
      tf_end: null,
      entrydate: "2020-04-07 10:32:08",
      stamp_id: null,
      FILE_EXTENSHION_ID: "1",
      MAPPING_IDS: [
        { ID: "243", NAME: "Financial" },
        { ID: "245", NAME: "markets" },
      ],
      TF_START: null,
      page_url: null,
      link: "",
      extra2: "Partners",
      file_extenshion_id: "1",
      enity_id: "602902",
      display_name: "Ultricies leo integer malesuada",
      FILE_NAME2: null,
      MAP_USER_ID: null,
      POST_DATE_FORMAT: "07/01/2019",
    },
    {
      extra1: "Health",
      STATUS: "1",
      ENITY_ID: "602901",
      HREF: "/cgi-bin/r/util/fg_pickup.pl?ENITY_ID=602901",
      post_date_format: "04/01/2020",
      terms_id: null,
      TF_END: null,
      ENTRYDATE: "2020-04-07 10:25:17",
      archive_status: "0",
      EXTRA1: "Health",
      mail_processed: "0",
      sort_order: "0",
      MAIL_PROCESSED: "0",
      TERMS_ID: null,
      long_desc:
        "Lorem ipsum dolor sit amet, consectetur adipiscing elit, sed do eiusmod tempor incididunt ut labore et dolore magna aliqua. Tortor vitae purus faucibus ornare suspendisse sed nisi lacus sed. Sed vulputate odio ut enim blandit volutpat maecenas. Lacus vel facilisis volutpat est velit. Facilisis magna etiam tempor orci eu lobortis elementum nibh tellus. Sit amet purus gravida quis blandit turpis. Quam viverra orci sagittis eu volutpat odio facilisis. Quis viverra nibh cras pulvinar mattis. Nibh tellus molestie nunc non blandit massa. Duis ut diam quam nulla. Ligula ullamcorper malesuada proin libero nunc. Viverra nam libero justo laoreet sit amet cursus sit amet. Maecenas sed enim ut sem. Mauris ultrices eros in cursus turpis. Condimentum lacinia quis vel eros donec ac odio tempor. Mattis vulputate enim nulla aliquet porttitor lacus luctus. Dictum sit amet justo donec enim diam vulputate ut. Facilisis magna etiam tempor orci eu lobortis elementum. Pulvinar pellentesque habitant morbi tristique senectus et netus et.<br /><br />Ultricies leo integer malesuada nunc vel risus commodo viverra maecenas. Amet consectetur adipiscing elit ut aliquam purus sit amet. In fermentum et sollicitudin ac orci phasellus egestas tellus rutrum. Non curabitur gravida arcu ac tortor dignissim convallis aenean et. Bibendum ut tristique et egestas. Phasellus vestibulum lorem sed risus ultricies. Facilisi morbi tempus iaculis urna id volutpat. Amet luctus venenatis lectus magna fringilla urna porttitor. Volutpat lacus laoreet non curabitur gravida arcu ac tortor. Odio pellentesque diam volutpat commodo sed egestas egestas fringilla. Id diam maecenas ultricies mi eget mauris pharetra et ultrices. Venenatis tellus in metus vulputate eu scelerisque. Nunc sed id semper risus in hendrerit gravida rutrum. Sed lectus vestibulum mattis ullamcorper velit sed ullamcorper morbi tincidunt. Lectus quam id leo in vitae turpis massa.<br /><br />Mi bibendum neque egestas congue. Id leo in vitae turpis massa. Condimentum lacinia quis vel eros donec ac odio tempor orci. Condimentum lacinia quis vel eros donec ac odio tempor. Eu consequat ac felis donec et odio pellentesque diam volutpat. Id consectetur purus ut faucibus pulvinar elementum. Pulvinar mattis nunc sed blandit libero volutpat sed cras ornare. Nisl condimentum id venenatis a condimentum. Congue quisque egestas diam in arcu. Nunc non blandit massa enim nec. Nisl condimentum id venenatis a condimentum vitae sapien pellentesque. In fermentum et sollicitudin ac orci phasellus.<br /><br />Ultrices vitae auctor eu augue. Gravida dictum fusce ut placerat orci nulla pellentesque dignissim. Duis at tellus at urna condimentum mattis. Id donec ultrices tincidunt arcu non. Lectus nulla at volutpat diam ut venenatis tellus in metus. Orci ac auctor augue mauris augue neque gravida in fermentum. Pulvinar pellentesque habitant morbi tristique senectus et netus et malesuada. Augue eget arcu dictum varius duis at consectetur lorem donec. Ut enim blandit volutpat maecenas. Et tortor consequat id porta nibh. Libero justo laoreet sit amet cursus sit amet dictum sit. Ut pharetra sit amet aliquam id diam maecenas. Ultricies tristique nulla aliquet enim tortor at auctor urna. Cras ornare arcu dui vivamus arcu felis bibendum ut tristique. Dictum fusce ut placerat orci nulla pellentesque dignissim. Hendrerit dolor magna eget est lorem ipsum dolor. Quis ipsum suspendisse ultrices gravida dictum.<br /><br />Viverra nam libero justo laoreet sit amet cursus. Et netus et malesuada fames ac turpis egestas integer eget. Viverra mauris in aliquam sem fringilla. Ut eu sem integer vitae justo. Nunc vel risus commodo viverra maecenas accumsan. Platea dictumst vestibulum rhoncus est. Vel elit scelerisque mauris pellentesque pulvinar pellentesque habitant morbi. Odio euismod lacinia at quis risus sed vulputate odio. Leo vel orci porta non pulvinar. Integer enim neque volutpat ac tincidunt vitae semper. Suspendisse interdum consectetur libero id. Volutpat ac tincidunt vitae semper quis lectus nulla at volutpat. Orci a scelerisque purus semper eget duis at. Ligula ullamcorper malesuada proin libero nunc consequat interdum. Tincidunt id aliquet risus feugiat. Tincidunt vitae semper quis lectus.",
      PRIV_ID: null,
      POST_DATE: "2020-04-01 00:00:00",
      extra3: "Insights",
      post_date: "2020-04-01 00:00:00",
      user_id: "14",
      SOURCE: null,
      source: null,
      PAGE_URL: null,
      author: "Anna Doe",
      USER_ID: "14",
      ARCHIVE_STATUS: "0",
      STAMP_ID: null,
      map_user_id: null,
      SHORT_DESC:
        "Lorem ipsum dolor sit amet, consectetur adipiscing elit, sed do eiusmod tempor incididunt ut labore et dolore magna aliqua",
      group_id: "4050",
      FILE_HREF:
        "/data/documents/FG/sanctuary/resources/602901_photo-1586199048510-60f2d45dfebe.webp",
      year: "2020",
      SORT_ORDER: "0",
      ENTRYDATE_FORMAT: "04/07/2020",
      LONG_DESC:
        "Lorem ipsum dolor sit amet, consectetur adipiscing elit, sed do eiusmod tempor incididunt ut labore et dolore magna aliqua. Tortor vitae purus faucibus ornare suspendisse sed nisi lacus sed. Sed vulputate odio ut enim blandit volutpat maecenas. Lacus vel facilisis volutpat est velit. Facilisis magna etiam tempor orci eu lobortis elementum nibh tellus. Sit amet purus gravida quis blandit turpis. Quam viverra orci sagittis eu volutpat odio facilisis. Quis viverra nibh cras pulvinar mattis. Nibh tellus molestie nunc non blandit massa. Duis ut diam quam nulla. Ligula ullamcorper malesuada proin libero nunc. Viverra nam libero justo laoreet sit amet cursus sit amet. Maecenas sed enim ut sem. Mauris ultrices eros in cursus turpis. Condimentum lacinia quis vel eros donec ac odio tempor. Mattis vulputate enim nulla aliquet porttitor lacus luctus. Dictum sit amet justo donec enim diam vulputate ut. Facilisis magna etiam tempor orci eu lobortis elementum. Pulvinar pellentesque habitant morbi tristique senectus et netus et.<br /><br />Ultricies leo integer malesuada nunc vel risus commodo viverra maecenas. Amet consectetur adipiscing elit ut aliquam purus sit amet. In fermentum et sollicitudin ac orci phasellus egestas tellus rutrum. Non curabitur gravida arcu ac tortor dignissim convallis aenean et. Bibendum ut tristique et egestas. Phasellus vestibulum lorem sed risus ultricies. Facilisi morbi tempus iaculis urna id volutpat. Amet luctus venenatis lectus magna fringilla urna porttitor. Volutpat lacus laoreet non curabitur gravida arcu ac tortor. Odio pellentesque diam volutpat commodo sed egestas egestas fringilla. Id diam maecenas ultricies mi eget mauris pharetra et ultrices. Venenatis tellus in metus vulputate eu scelerisque. Nunc sed id semper risus in hendrerit gravida rutrum. Sed lectus vestibulum mattis ullamcorper velit sed ullamcorper morbi tincidunt. Lectus quam id leo in vitae turpis massa.<br /><br />Mi bibendum neque egestas congue. Id leo in vitae turpis massa. Condimentum lacinia quis vel eros donec ac odio tempor orci. Condimentum lacinia quis vel eros donec ac odio tempor. Eu consequat ac felis donec et odio pellentesque diam volutpat. Id consectetur purus ut faucibus pulvinar elementum. Pulvinar mattis nunc sed blandit libero volutpat sed cras ornare. Nisl condimentum id venenatis a condimentum. Congue quisque egestas diam in arcu. Nunc non blandit massa enim nec. Nisl condimentum id venenatis a condimentum vitae sapien pellentesque. In fermentum et sollicitudin ac orci phasellus.<br /><br />Ultrices vitae auctor eu augue. Gravida dictum fusce ut placerat orci nulla pellentesque dignissim. Duis at tellus at urna condimentum mattis. Id donec ultrices tincidunt arcu non. Lectus nulla at volutpat diam ut venenatis tellus in metus. Orci ac auctor augue mauris augue neque gravida in fermentum. Pulvinar pellentesque habitant morbi tristique senectus et netus et malesuada. Augue eget arcu dictum varius duis at consectetur lorem donec. Ut enim blandit volutpat maecenas. Et tortor consequat id porta nibh. Libero justo laoreet sit amet cursus sit amet dictum sit. Ut pharetra sit amet aliquam id diam maecenas. Ultricies tristique nulla aliquet enim tortor at auctor urna. Cras ornare arcu dui vivamus arcu felis bibendum ut tristique. Dictum fusce ut placerat orci nulla pellentesque dignissim. Hendrerit dolor magna eget est lorem ipsum dolor. Quis ipsum suspendisse ultrices gravida dictum.<br /><br />Viverra nam libero justo laoreet sit amet cursus. Et netus et malesuada fames ac turpis egestas integer eget. Viverra mauris in aliquam sem fringilla. Ut eu sem integer vitae justo. Nunc vel risus commodo viverra maecenas accumsan. Platea dictumst vestibulum rhoncus est. Vel elit scelerisque mauris pellentesque pulvinar pellentesque habitant morbi. Odio euismod lacinia at quis risus sed vulputate odio. Leo vel orci porta non pulvinar. Integer enim neque volutpat ac tincidunt vitae semper. Suspendisse interdum consectetur libero id. Volutpat ac tincidunt vitae semper quis lectus nulla at volutpat. Orci a scelerisque purus semper eget duis at. Ligula ullamcorper malesuada proin libero nunc consequat interdum. Tincidunt id aliquet risus feugiat. Tincidunt vitae semper quis lectus.",
      FILE2_HREF: "",
      file_name: "602901_photo-1586199048510-60f2d45dfebe.webp",
      short_desc:
        "Lorem ipsum dolor sit amet, consectetur adipiscing elit, sed do eiusmod tempor incididunt ut labore et dolore magna aliqua",
      entrydate_format: "04/07/2020",
      file_name2: null,
      EXTRA2: "Partners",
      AUTHOR: "Anna Doe",
      LINK: "",
      EXTRA3: "Insights",
      DISPLAY_NAME: "Lorem ipsum dolor",
      FILE_NAME: "602901_photo-1586199048510-60f2d45dfebe.webp",
      priv_id: null,
      YEAR: "2020",
      status: "1",
      GROUP_ID: "4050",
      tf_start: null,
      tf_end: null,
      entrydate: "2020-04-07 10:25:17",
      stamp_id: null,
      FILE_EXTENSHION_ID: "1",
      MAPPING_IDS: [
        { ID: "247", NAME: "education" },
        { ID: "243", NAME: "Financial" },
      ],
      TF_START: null,
      page_url: null,
      link: "",
      extra2: "Partners",
      file_extenshion_id: "1",
      enity_id: "602901",
      display_name: "Lorem ipsum dolor",
      FILE_NAME2: null,
      MAP_USER_ID: null,
      POST_DATE_FORMAT: "04/01/2020",
    },
  ],
};
